2025-03-03 19:45:22,336 INFO    MainThread:44069 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-03 19:45:22,336 INFO    MainThread:44069 [wandb_setup.py:_flush():67] Configure stats pid to 44069
2025-03-03 19:45:22,336 INFO    MainThread:44069 [wandb_setup.py:_flush():67] Loading settings from /home/inae/.config/wandb/settings
2025-03-03 19:45:22,337 INFO    MainThread:44069 [wandb_setup.py:_flush():67] Loading settings from /mnt/c/Users/ihkoo/programming/CRLQAS/jax_noisy/wandb/settings
2025-03-03 19:45:22,337 INFO    MainThread:44069 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-03 19:45:22,337 INFO    MainThread:44069 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /mnt/c/Users/ihkoo/programming/CRLQAS/jax_noisy/wandb/run-20250303_194522-s5d881tf/logs/debug.log
2025-03-03 19:45:22,341 INFO    MainThread:44069 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /mnt/c/Users/ihkoo/programming/CRLQAS/jax_noisy/wandb/run-20250303_194522-s5d881tf/logs/debug-internal.log
2025-03-03 19:45:22,341 INFO    MainThread:44069 [wandb_init.py:init():761] calling init triggers
2025-03-03 19:45:22,341 INFO    MainThread:44069 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'general': {'episodes': 10000}, 'env': {'num_qubits': 2, 'num_layers': 40, 'err_mitig': 0.0, 'rand_halt': 1.0, 'n_shots': 1000.0, 'noise_models': '["mumbai_median"]', 'noise_values': [0.001, 0.005], 'fake_min_energy': -1.320446365758868, 'fn_type': 'incremental_with_fixed_ends', 'accept_err': -0.35119018, 'shift_threshold_time': 500, 'shift_threshold_ball': 0.0005, 'success_thresh': 25, 'succ_radius_shift': 10, 'succes_switch': -0.35119018, 'thresholds': [], 'switch_episodes': [], 'curriculum_type': 'MovingThreshold'}, 'problem': {'ham_type': 'H2', 'geometry': 'H .0 .0 .0; H .0 .0 0.7414', 'taper': 1, 'mapping': 'jordan_wigner'}, 'agent': {'batch_size': 1000, 'memory_size': 20000, 'neurons': [1000, 1000, 1000, 1000, 1000], 'dropout': 0.0, 'learning_rate': 0.0003, 'angles': 0, 'en_state': 1, 'agent_type': 'DeepQNstep', 'agent_class': 'DQN_Nstep', 'n_step': 5, 'init_net': 0, 'update_target_net': 500, 'final_gamma': 0.005, 'epsilon_decay': 0.99995, 'epsilon_min': 0.05, 'epsilon_restart': 1.0}, 'non_local_opt': {'a': 1.2104, 'alpha': 0.9531, 'c': 0.1039, 'gamma': 0.0984, 'lamda': 0.9277, 'beta_1': 0.9414, 'beta_2': 0.9983, 'maxfev': 500.0, 'global_iters': 100, 'method': 'SPSA', 'optim_alg': '0'}, '_wandb': {}}
2025-03-03 19:45:22,341 INFO    MainThread:44069 [wandb_init.py:init():784] starting backend
2025-03-03 19:45:22,342 INFO    MainThread:44069 [wandb_init.py:init():788] sending inform_init request
2025-03-03 19:45:22,348 INFO    MainThread:44069 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-03 19:45:22,349 INFO    MainThread:44069 [wandb_init.py:init():803] backend started and connected
2025-03-03 19:45:22,351 INFO    MainThread:44069 [wandb_init.py:init():896] updated telemetry
2025-03-03 19:45:22,361 INFO    MainThread:44069 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-03 19:45:22,910 INFO    MainThread:44069 [wandb_init.py:init():995] starting run threads in backend
2025-03-03 19:45:23,142 INFO    MainThread:44069 [wandb_run.py:_console_start():2377] atexit reg
2025-03-03 19:45:23,143 INFO    MainThread:44069 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-03 19:45:23,143 INFO    MainThread:44069 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-03 19:45:23,144 INFO    MainThread:44069 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-03 19:45:23,145 INFO    MainThread:44069 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-03 19:45:25,585 WARNING MsgRouterThr:44069 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/home/inae/miniconda3/envs/CRLQAS/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "/home/inae/miniconda3/envs/CRLQAS/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/home/inae/miniconda3/envs/CRLQAS/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/inae/miniconda3/envs/CRLQAS/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
  File "/home/inae/miniconda3/envs/CRLQAS/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-03 19:45:25,586 INFO    MsgRouterThr:44069 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
